from typing import List, Dict, Sequence

import numpy as np

from medical_image.algorithms.algorithm import Algorithm
from medical_image.data.cluster import ClusterFeatures
from medical_image.data.physical_features import (
    CandidatePhysicalFeatures,
    SpatialParticleFeatures,
)


class ClusterReasoningAlgorithm(Algorithm):
    """
    Cluster-level reasoning over candidate particles.

    This algorithm consumes:

        1. CandidatePhysicalFeatures
        2. SpatialParticleFeatures

    produced by Steps 7 and 9.

    It does NOT inspect the mammogram pixels.

    Step 9 determines local spatial relationships.

    Step 10 interprets groups of spatially related particles.

    The algorithm computes:

        - cluster size
        - spatial extent
        - density
        - pairwise distance statistics
        - nearest-neighbor statistics
        - particle evidence statistics
        - particle shape statistics
        - spatial eccentricity
        - compactness
        - regularity
        - cluster-level evidence
        - final cluster score
    """

    def __init__(
        self,
        min_particles: int = 3,
        density_radius: float = 20.0,
        min_density: float = 0.001,
        particle_score_threshold: float = 2.0,
        device: str = "cpu",
    ):
        super().__init__(
            device=device
        )

        if min_particles < 1:
            raise ValueError(
                "min_particles must be >= 1."
            )

        if density_radius <= 0:
            raise ValueError(
                "density_radius must be > 0."
            )

        if min_density < 0:
            raise ValueError(
                "min_density must be >= 0."
            )

        self.min_particles = int(
            min_particles
        )

        self.density_radius = float(
            density_radius
        )

        self.min_density = float(
            min_density
        )

        self.particle_score_threshold = float(
            particle_score_threshold
        )

    # ======================================================
    # Particle score
    # ======================================================

    @staticmethod
    def _particle_score(
        particle: CandidatePhysicalFeatures,
    ) -> float:
        """
        Retrieve the best available particle evidence.

        At the current stage, CandidatePhysicalFeatures
        does not contain a final particle_score.

        Therefore robust_peak_z is used.

        Once a Particle object with particle_score exists,
        this function can be replaced without changing
        the cluster reasoning architecture.
        """

        if hasattr(
            particle,
            "particle_score",
        ):
            return float(
                particle.particle_score
            )

        return float(
            particle.robust_peak_z
        )

    # ======================================================
    # Group particles
    # ======================================================

    @staticmethod
    def _group_particles(
        spatial_features: Sequence[
            SpatialParticleFeatures
        ],
    ) -> Dict[
        int,
        List[int],
    ]:
        """
        Group particle indices according to the preliminary
        spatial group generated by Step 9.
        """

        groups: Dict[
            int,
            List[int],
        ] = {}

        for index, feature in enumerate(
            spatial_features
        ):

            group_id = (
                feature.spatial_group_id
            )

            if group_id not in groups:
                groups[group_id] = []

            groups[group_id].append(
                index
            )

        return groups

    # ======================================================
    # Spatial extent
    # ======================================================

    @staticmethod
    def _spatial_extent(
        positions: np.ndarray,
    ):
        """
        Calculate axis-aligned spatial extent.

        positions:
            [N, 2]

        Returns:
            extent_x
            extent_y
            diagonal extent
        """

        if len(positions) == 1:

            return (
                0.0,
                0.0,
                0.0,
            )

        min_x = np.min(
            positions[:, 0]
        )

        max_x = np.max(
            positions[:, 0]
        )

        min_y = np.min(
            positions[:, 1]
        )

        max_y = np.max(
            positions[:, 1]
        )

        extent_x = (
            max_x - min_x
        )

        extent_y = (
            max_y - min_y
        )

        diagonal = float(
            np.sqrt(
                extent_x ** 2
                + extent_y ** 2
            )
        )

        return (
            float(extent_x),
            float(extent_y),
            diagonal,
        )

    # ======================================================
    # Spatial eccentricity
    # ======================================================

    @staticmethod
    def _spatial_eccentricity(
        positions: np.ndarray,
    ) -> float:
        """
        Estimate the eccentricity of the particle
        distribution.

        A compact roughly circular cluster has a value
        closer to zero.

        An elongated distribution approaches one.
        """

        if len(positions) < 2:
            return 0.0

        centered = (
            positions
            - positions.mean(
                axis=0,
                keepdims=True,
            )
        )

        covariance = np.cov(
            centered.T
        )

        if covariance.ndim == 0:
            return 0.0

        eigenvalues = np.linalg.eigvalsh(
            covariance
        )

        eigenvalues = np.clip(
            eigenvalues,
            0.0,
            None,
        )

        lambda_min = float(
            eigenvalues[0]
        )

        lambda_max = float(
            eigenvalues[-1]
        )

        if lambda_max <= 1e-12:
            return 0.0

        eccentricity = np.sqrt(
            max(
                0.0,
                1.0
                - lambda_min
                / lambda_max,
            )
        )

        return float(
            np.clip(
                eccentricity,
                0.0,
                1.0,
            )
        )

    # ======================================================
    # Pairwise distances
    # ======================================================

    @staticmethod
    def _pairwise_statistics(
            positions: np.ndarray,
            max_pairs: int = 100_000,
    ):
        """
        Memory-safe pairwise statistics.

        Exact for small groups.

        Approximate for large groups using a deterministic
        spatially representative subset.
        """

        n = len(positions)

        if n < 2:
            return (
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            )

        total_pairs = (
                              n * (n - 1)
                      ) // 2

        # --------------------------------------------------
        # Exact case
        # --------------------------------------------------

        if total_pairs <= max_pairs:
            from scipy.spatial.distance import pdist

            distances = pdist(
                positions
            )

            return (
                float(np.mean(distances)),
                float(np.median(distances)),
                float(np.max(distances)),
                float(np.percentile(distances, 25)),
                float(np.percentile(distances, 75)),
            )

        # --------------------------------------------------
        # Large group
        #
        # Select a bounded number of particles.
        # --------------------------------------------------

        max_particles = int(
            np.sqrt(
                2 * max_pairs
            )
        )

        max_particles = max(
            max_particles,
            2,
        )

        if n > max_particles:

            indices = np.linspace(
                0,
                n - 1,
                max_particles,
                dtype=np.int64,
            )

            sampled_positions = (
                positions[indices]
            )

        else:

            sampled_positions = positions

        # --------------------------------------------------
        # Pairwise distances only on bounded subset.
        # --------------------------------------------------

        from scipy.spatial.distance import pdist

        distances = pdist(
            sampled_positions
        )

        return (
            float(np.mean(distances)),
            float(np.median(distances)),
            float(np.max(distances)),
            float(np.percentile(distances, 25)),
            float(np.percentile(distances, 75)),
        )

    # ======================================================
    # Density
    # ======================================================

    def _density(
        self,
        particle_count: int,
        extent_x: float,
        extent_y: float,
    ) -> float:
        """
        Estimate cluster density.

        The bounding-box area is used rather than the entire
        mammogram.

        A small cluster containing many particles therefore
        receives higher density than a sparse large group.
        """

        if particle_count <= 1:
            return 0.0

        area = (
            extent_x
            * extent_y
        )

        # Avoid zero-area clusters such as particles lying
        # on exactly the same row or column.
        area = max(
            area,
            np.pi
            * self.density_radius ** 2,
        )

        return float(
            particle_count
            / area
        )

    # ======================================================
    # Density score
    # ======================================================

    def _density_score(
        self,
        density: float,
    ) -> float:
        """
        Convert density into a bounded [0,1] score.

        This is intentionally a smooth heuristic rather
        than a hard classifier.
        """

        if density <= 0:
            return 0.0

        score = (
            density
            / (
                density
                + self.min_density
            )
        )

        return float(
            np.clip(
                score,
                0.0,
                1.0,
            )
        )

    # ======================================================
    # Compactness
    # ======================================================

    @staticmethod
    def _compactness_score(
        mean_pairwise_distance: float,
        spatial_extent: float,
    ) -> float:
        """
        Measure how tightly the particles occupy the
        cluster's spatial extent.

        Smaller internal distances relative to the total
        extent imply a more compact structure.
        """

        if spatial_extent <= 1e-8:
            return 1.0

        ratio = (
            mean_pairwise_distance
            / spatial_extent
        )

        score = np.exp(
            -ratio
        )

        return float(
            np.clip(
                score,
                0.0,
                1.0,
            )
        )

    # ======================================================
    # Regularity
    # ======================================================

    @staticmethod
    def _regularity_score(
        nearest_distances: np.ndarray,
    ) -> float:
        """
        Measure consistency of nearest-neighbor spacing.

        Low variation in nearest-neighbor distances gives
        higher regularity.

        This should NOT be interpreted as requiring perfectly
        regular biological structures. It is only one weak
        descriptor.
        """

        if len(
            nearest_distances
        ) <= 1:

            return 1.0

        mean_distance = np.mean(
            nearest_distances
        )

        if mean_distance <= 1e-8:
            return 1.0

        coefficient_variation = (
            np.std(
                nearest_distances
            )
            / mean_distance
        )

        score = 1.0 / (
            1.0
            + coefficient_variation
        )

        return float(
            np.clip(
                score,
                0.0,
                1.0,
            )
        )

    # ======================================================
    # Particle evidence
    # ======================================================

    @staticmethod
    def _particle_evidence_score(
        particle_scores: np.ndarray,
        threshold: float,
    ) -> float:
        """
        Estimate how strongly the particles themselves
        support a microcalcification interpretation.

        Uses the fraction of particles above the current
        local-evidence threshold.

        This is deliberately different from the mean score.
        """

        if len(
            particle_scores
        ) == 0:

            return 0.0

        fraction = np.mean(
            particle_scores
            >= threshold
        )

        return float(
            np.clip(
                fraction,
                0.0,
                1.0,
            )
        )

    # ======================================================
    # Geometry score
    # ======================================================

    @staticmethod
    def _geometry_score(
        spatial_eccentricity: float,
        spatial_compactness: float,
    ) -> float:
        """
        Combine compactness and spatial shape.

        Compact and non-extremely-elongated groups receive
        higher scores.

        This is only a geometric descriptor. It is not a
        diagnostic classifier.
        """

        eccentricity_score = (
            1.0
            - np.clip(
                spatial_eccentricity,
                0.0,
                1.0,
            )
        )

        return float(
            np.clip(
                0.5
                * (
                    spatial_compactness
                    + eccentricity_score
                ),
                0.0,
                1.0,
            )
        )

    # ======================================================
    # Cluster score
    # ======================================================

    @staticmethod
    def _cluster_score(
        density_score: float,
        compactness_score: float,
        particle_evidence_score: float,
        geometry_score: float,
    ) -> float:
        """
        Combine cluster-level evidence.

        Current weighting:

            density          25%
            compactness      25%
            particle evidence 35%
            geometry         15%

        These weights are intentionally explicit and easy
        to replace later with a calibrated formulation.
        """

        score = (
            0.25
            * density_score

            + 0.25
            * compactness_score

            + 0.35
            * particle_evidence_score

            + 0.15
            * geometry_score
        )

        return float(
            np.clip(
                score,
                0.0,
                1.0,
            )
        )

    # ======================================================
    # Main
    # ======================================================

    def apply(
        self,
        physical_features: List[
            CandidatePhysicalFeatures
        ],
        spatial_features: List[
            SpatialParticleFeatures
        ],
    ) -> List[ClusterFeatures]:

        if physical_features is None:
            raise ValueError(
                "physical_features must not be None."
            )

        if spatial_features is None:
            raise ValueError(
                "spatial_features must not be None."
            )

        if len(
            physical_features
        ) != len(
            spatial_features
        ):
            raise ValueError(
                "physical_features and "
                "spatial_features must contain "
                "the same number of particles."
            )

        if len(
            physical_features
        ) == 0:

            return []

        # --------------------------------------------------
        # Verify that both representations refer to the
        # same particles.
        # --------------------------------------------------

        physical_labels = [
            feature.label
            for feature in physical_features
        ]

        spatial_labels = [
            feature.label
            for feature in spatial_features
        ]

        if physical_labels != spatial_labels:

            raise ValueError(
                "physical_features and "
                "spatial_features must have "
                "identical particle ordering."
            )

        # --------------------------------------------------
        # Group particles using Step 9's spatial graph.
        # --------------------------------------------------

        groups = (
            self._group_particles(
                spatial_features
            )
        )

        results = []

        # --------------------------------------------------
        # Process each preliminary spatial group.
        # --------------------------------------------------

        for cluster_id, indices in groups.items():

            particles = [
                physical_features[i]
                for i in indices
            ]

            spatial = [
                spatial_features[i]
                for i in indices
            ]

            particle_count = len(
                particles
            )

            # --------------------------------------------------
            # Particle positions
            # --------------------------------------------------

            positions = np.asarray(
                [
                    (
                        particle.center_x,
                        particle.center_y,
                    )
                    for particle in particles
                ],
                dtype=np.float64,
            )

            # --------------------------------------------------
            # Cluster center
            # --------------------------------------------------

            center_x = float(
                np.mean(
                    positions[:, 0]
                )
            )

            center_y = float(
                np.mean(
                    positions[:, 1]
                )
            )

            # --------------------------------------------------
            # Spatial extent
            # --------------------------------------------------

            (
                extent_x,
                extent_y,
                spatial_extent,
            ) = self._spatial_extent(
                positions
            )

            # --------------------------------------------------
            # Pairwise distances
            # --------------------------------------------------

            (
                mean_pairwise_distance,
                median_pairwise_distance,
                max_pairwise_distance,
                distance_q25,
                distance_q75,
            ) = self._pairwise_statistics(
                positions
            )

            # --------------------------------------------------
            # Density
            # --------------------------------------------------

            density = self._density(
                particle_count,
                extent_x,
                extent_y,
            )

            density_score = (
                self._density_score(
                    density
                )
            )

            # --------------------------------------------------
            # Nearest-neighbor statistics
            #
            # Step 9 already calculated these.
            # We aggregate them instead of recomputing them.
            # --------------------------------------------------

            nearest_distances = np.asarray(
                [
                    feature.nearest_neighbor_distance
                    for feature in spatial
                    if np.isfinite(
                        feature.nearest_neighbor_distance
                    )
                ],
                dtype=np.float64,
            )

            if len(
                nearest_distances
            ) == 0:

                mean_nearest_neighbor_distance = (
                    float("inf")
                )

                median_nearest_neighbor_distance = (
                    float("inf")
                )

                std_nearest_neighbor_distance = 0.0

                min_nearest_neighbor_distance = (
                    float("inf")
                )

                max_nearest_neighbor_distance = (
                    float("inf")
                )

            else:

                mean_nearest_neighbor_distance = (
                    float(
                        np.mean(
                            nearest_distances
                        )
                    )
                )

                median_nearest_neighbor_distance = (
                    float(
                        np.median(
                            nearest_distances
                        )
                    )
                )

                std_nearest_neighbor_distance = (
                    float(
                        np.std(
                            nearest_distances
                        )
                    )
                )

                min_nearest_neighbor_distance = (
                    float(
                        np.min(
                            nearest_distances
                        )
                    )
                )

                max_nearest_neighbor_distance = (
                    float(
                        np.max(
                            nearest_distances
                        )
                    )
                )

            # --------------------------------------------------
            # Compactness
            # --------------------------------------------------

            compactness_score = (
                self._compactness_score(
                    mean_pairwise_distance,
                    spatial_extent,
                )
            )

            # --------------------------------------------------
            # Regularity
            # --------------------------------------------------

            spatial_regular = (
                self._regularity_score(
                    nearest_distances
                )
            )

            # --------------------------------------------------
            # Spatial eccentricity
            # --------------------------------------------------

            spatial_eccentricity = (
                self._spatial_eccentricity(
                    positions
                )
            )

            # --------------------------------------------------
            # Particle evidence
            # --------------------------------------------------

            particle_scores = np.asarray(
                [
                    self._particle_score(
                        particle
                    )
                    for particle in particles
                ],
                dtype=np.float64,
            )

            mean_particle_score = float(
                np.mean(
                    particle_scores
                )
            )

            median_particle_score = float(
                np.median(
                    particle_scores
                )
            )

            std_particle_score = float(
                np.std(
                    particle_scores
                )
            )

            min_particle_score = float(
                np.min(
                    particle_scores
                )
            )

            max_particle_score = float(
                np.max(
                    particle_scores
                )
            )

            particle_evidence_score = (
                self._particle_evidence_score(
                    particle_scores,
                    self.particle_score_threshold,
                )
            )

            # --------------------------------------------------
            # Particle shape statistics
            # --------------------------------------------------

            circularities = np.asarray(
                [
                    particle.circularity
                    for particle in particles
                ],
                dtype=np.float64,
            )

            eccentricities = np.asarray(
                [
                    particle.eccentricity
                    for particle in particles
                ],
                dtype=np.float64,
            )

            solidities = np.asarray(
                [
                    particle.solidity
                    for particle in particles
                ],
                dtype=np.float64,
            )

            diameters = np.asarray(
                [
                    particle.equivalent_diameter
                    for particle in particles
                ],
                dtype=np.float64,
            )

            mean_circularity = float(
                np.mean(
                    circularities
                )
            )

            mean_eccentricity = float(
                np.mean(
                    eccentricities
                )
            )

            mean_solidity = float(
                np.mean(
                    solidities
                )
            )

            mean_equivalent_diameter = float(
                np.mean(
                    diameters
                )
            )

            # --------------------------------------------------
            # Geometry
            # --------------------------------------------------

            geometry_score = (
                self._geometry_score(
                    spatial_eccentricity,
                    compactness_score,
                )
            )

            # --------------------------------------------------
            # Final cluster score
            # --------------------------------------------------

            cluster_score = (
                self._cluster_score(
                    density_score,
                    compactness_score,
                    particle_evidence_score,
                    geometry_score,
                )
            )

            # --------------------------------------------------
            # Cluster decision
            #
            # Do not use cluster_score alone.
            #
            # A cluster must also contain enough particles.
            # --------------------------------------------------

            is_cluster = (
                particle_count
                >= self.min_particles
                and density
                >= self.min_density
            )

            # --------------------------------------------------
            # Build cluster object
            # --------------------------------------------------

            results.append(
                ClusterFeatures(
                    cluster_id=int(
                        cluster_id
                    ),

                    particle_labels=[
                        particle.label
                        for particle in particles
                    ],

                    particle_count=(
                        particle_count
                    ),

                    center_y=center_y,
                    center_x=center_x,

                    extent_y=extent_y,
                    extent_x=extent_x,

                    spatial_extent=(
                        spatial_extent
                    ),

                    density=density,

                    mean_nearest_neighbor_distance=(
                        mean_nearest_neighbor_distance
                    ),

                    median_nearest_neighbor_distance=(
                        median_nearest_neighbor_distance
                    ),

                    std_nearest_neighbor_distance=(
                        std_nearest_neighbor_distance
                    ),

                    min_nearest_neighbor_distance=(
                        min_nearest_neighbor_distance
                    ),

                    max_nearest_neighbor_distance=(
                        max_nearest_neighbor_distance
                    ),

                    mean_pairwise_distance=(
                        mean_pairwise_distance
                    ),

                    median_pairwise_distance=(
                        median_pairwise_distance
                    ),

                    max_pairwise_distance=(
                        max_pairwise_distance
                    ),

                    distance_q25=distance_q25,
                    distance_q75=distance_q75,

                    mean_particle_score=(
                        mean_particle_score
                    ),

                    median_particle_score=(
                        median_particle_score
                    ),

                    std_particle_score=(
                        std_particle_score
                    ),

                    min_particle_score=(
                        min_particle_score
                    ),

                    max_particle_score=(
                        max_particle_score
                    ),

                    mean_circularity=(
                        mean_circularity
                    ),

                    mean_eccentricity=(
                        mean_eccentricity
                    ),

                    mean_solidity=(
                        mean_solidity
                    ),

                    mean_equivalent_diameter=(
                        mean_equivalent_diameter
                    ),

                    spatial_eccentricity=(
                        spatial_eccentricity
                    ),

                    spatial_compactness=(
                        compactness_score
                    ),

                    spatial_regularity=(
                        spatial_regular
                    ),

                    density_score=(
                        density_score
                    ),

                    compactness_score=(
                        compactness_score
                    ),

                    particle_evidence_score=(
                        particle_evidence_score
                    ),

                    geometry_score=(
                        geometry_score
                    ),

                    cluster_score=(
                        cluster_score
                    ),

                    is_cluster=(
                        is_cluster
                    ),
                )
            )

        return results