from typing import Dict, List

import numpy as np
import torch
from scipy import ndimage

from medical_image.data.decision import FinalMCOutput
from medical_image.algorithms.algorithm import Algorithm


class NativeResolutionSegmentationAlgorithm(Algorithm):
    """
    Step 13.

    Converts final particle/cluster decisions into
    native-resolution mammogram segmentation.

    No resizing.
    No downsampling.
    No interpolation.

    Inputs
    ------
    candidates:
        Native-resolution candidate mask.

    physical_features:
        CandidatePhysicalFeatures generated by Step 7.

    clusters:
        ClusterFeatures generated by Step 10.

    final_decision:
        FinalMCDecision generated by Step 12.

    Output
    ------
    FinalMCOutput containing:

        mc_mask
        mc_evidence
        particle_map
        cluster_map
        particle decisions
        cluster decisions
        confidence
    """

    def __init__(
        self,
        connectivity: int = 2,
        device: str = "cpu",
    ):
        super().__init__(
            device=device
        )

        if connectivity not in (1, 2, 3):
            raise ValueError(
                "connectivity must be 1, 2, or 3."
            )

        self.connectivity = connectivity

    # ==========================================================
    # Native candidate mask
    # ==========================================================

    @staticmethod
    def _prepare_candidate_mask(
        candidates,
    ) -> np.ndarray:
        """
        Convert candidate image to a native H×W boolean array.
        """

        data = (
            candidates.pixel_data
            .detach()
            .cpu()
        )

        while data.ndim > 2:

            data = data.squeeze(0)

        if data.ndim != 2:

            raise ValueError(
                "Candidate mask must be a 2D "
                "native-resolution image."
            )

        return (
            data.bool()
            .numpy()
        )

    # ==========================================================
    # Connected components
    # ==========================================================

    def _connected_components(
        self,
        candidate_mask: np.ndarray,
    ):
        """
        Recover connected candidate particles.

        Labels are generated directly on the original
        mammogram resolution.
        """

        if self.connectivity == 1:

            structure = ndimage.generate_binary_structure(
                2,
                1,
            )

        elif self.connectivity == 2:

            structure = ndimage.generate_binary_structure(
                2,
                2,
            )

        else:

            structure = np.ones(
                (3, 3),
                dtype=np.uint8,
            )

        component_map, num_components = (
            ndimage.label(
                candidate_mask,
                structure=structure,
            )
        )

        return (
            component_map,
            num_components,
        )

    # ==========================================================
    # Particle lookup
    # ==========================================================

    @staticmethod
    def _build_particle_lookup(
        physical_features,
    ) -> Dict[int, object]:

        return {
            int(feature.label): feature
            for feature in physical_features
        }

    # ==========================================================
    # Final particle lookup
    # ==========================================================

    @staticmethod
    def _build_final_particle_lookup(
        final_decision,
    ):

        return {
            int(decision.label): decision
            for decision
            in final_decision.particle_decisions
        }

    # ==========================================================
    # Cluster lookup
    # ==========================================================

    @staticmethod
    def _build_cluster_lookup(
        clusters,
    ):

        lookup = {}

        for cluster in clusters:

            for label in cluster.particle_labels:

                lookup[
                    int(label)
                ] = cluster

        return lookup

    # ==========================================================
    # Final cluster lookup
    # ==========================================================

    @staticmethod
    def _build_final_cluster_lookup(
        final_decision,
    ):

        return {
            int(decision.cluster_id): decision
            for decision
            in final_decision.cluster_decisions
        }

    # ==========================================================
    # Map candidate components to particle labels
    # ==========================================================

    @staticmethod
    def _match_components_to_particles(
        component_map: np.ndarray,
        physical_features,
    ) -> Dict[int, int]:
        """
        Associate connected components with the particle
        labels produced by LocalPhysicalAnalysis.

        The center of each physical candidate is used to
        identify its native-resolution component.

        Returns:

            component_id -> particle_label
        """

        component_to_particle = {}

        height, width = (
            component_map.shape
        )

        for feature in physical_features:

            y = int(
                round(
                    feature.center_y
                )
            )

            x = int(
                round(
                    feature.center_x
                )
            )

            # ----------------------------------------------
            # Protect against numerical boundary issues.
            # ----------------------------------------------

            y = max(
                0,
                min(
                    height - 1,
                    y,
                ),
            )

            x = max(
                0,
                min(
                    width - 1,
                    x,
                ),
            )

            component_id = int(
                component_map[
                    y,
                    x,
                ]
            )

            if component_id == 0:
                continue

            component_to_particle[
                component_id
            ] = int(
                feature.label
            )

        return component_to_particle

    # ==========================================================
    # Main
    # ==========================================================

    def apply(
        self,
        candidates,
        physical_features,
        clusters,
        final_decision,
    ) -> FinalMCOutput:

        if candidates is None:
            raise ValueError(
                "candidates must not be None."
            )

        if physical_features is None:
            raise ValueError(
                "physical_features must not be None."
            )

        if clusters is None:
            raise ValueError(
                "clusters must not be None."
            )

        if final_decision is None:
            raise ValueError(
                "final_decision must not be None."
            )

        # ======================================================
        # 1. Native candidate mask
        # ======================================================

        candidate_mask = (
            self._prepare_candidate_mask(
                candidates
            )
        )

        height, width = (
            candidate_mask.shape
        )

        # ======================================================
        # 2. Connected components
        # ======================================================

        component_map, num_components = (
            self._connected_components(
                candidate_mask
            )
        )

        # ======================================================
        # 3. Lookups
        # ======================================================

        particle_lookup = (
            self._build_particle_lookup(
                physical_features
            )
        )

        final_particle_lookup = (
            self._build_final_particle_lookup(
                final_decision
            )
        )

        cluster_lookup = (
            self._build_cluster_lookup(
                clusters
            )
        )

        final_cluster_lookup = (
            self._build_final_cluster_lookup(
                final_decision
            )
        )

        component_to_particle = (
            self._match_components_to_particles(
                component_map,
                physical_features,
            )
        )

        # ======================================================
        # 4. Allocate native-resolution outputs
        # ======================================================

        mc_mask = np.zeros(
            (height, width),
            dtype=np.bool_,
        )

        mc_evidence = np.zeros(
            (height, width),
            dtype=np.float32,
        )

        particle_map = np.zeros(
            (height, width),
            dtype=np.int32,
        )

        cluster_map = np.zeros(
            (height, width),
            dtype=np.int32,
        )

        # ======================================================
        # 5. Rasterize each physical particle
        # ======================================================

        for component_id, particle_label in (
            component_to_particle.items()
        ):

            particle_decision = (
                final_particle_lookup.get(
                    particle_label
                )
            )

            if particle_decision is None:
                continue

            pixels = (
                component_map
                == component_id
            )

            # --------------------------------------------------
            # Particle map
            # --------------------------------------------------

            particle_map[
                pixels
            ] = int(
                particle_label
            )

            # --------------------------------------------------
            # Find cluster
            # --------------------------------------------------

            cluster = (
                cluster_lookup.get(
                    particle_label
                )
            )

            if cluster is not None:

                cluster_id = int(
                    cluster.cluster_id
                )

                cluster_decision = (
                    final_cluster_lookup.get(
                        cluster_id
                    )
                )

            else:

                cluster_id = 0
                cluster_decision = None

            # --------------------------------------------------
            # Cluster map
            # --------------------------------------------------

            if cluster_id > 0:

                cluster_map[
                    pixels
                ] = cluster_id

            # --------------------------------------------------
            # Final particle evidence
            # --------------------------------------------------

            particle_score = float(
                np.clip(
                    particle_decision.final_score,
                    0.0,
                    1.0,
                )
            )

            cluster_score = 0.0

            if cluster_decision is not None:

                cluster_score = float(
                    np.clip(
                        cluster_decision.final_score,
                        0.0,
                        1.0,
                    )
                )

            # --------------------------------------------------
            # Combined pixel evidence
            # --------------------------------------------------

            if cluster_decision is not None:

                evidence = (
                    0.70
                    * particle_score
                    +
                    0.30
                    * cluster_score
                )

            else:

                evidence = (
                    0.80
                    * particle_score
                )

            evidence = float(
                np.clip(
                    evidence,
                    0.0,
                    1.0,
                )
            )

            mc_evidence[
                pixels
            ] = evidence

            # --------------------------------------------------
            # Final MC segmentation
            # --------------------------------------------------

            if (
                particle_decision
                .is_microcalcification
            ):

                if (
                    cluster_decision is None
                    or cluster_decision
                    .is_microcalcification_cluster
                ):

                    mc_mask[
                        pixels
                    ] = True

        # ======================================================
        # 6. Convert to tensors
        # ======================================================

        mc_mask_tensor = torch.from_numpy(
            mc_mask
        ).to(
            device=self.device
        )

        mc_evidence_tensor = torch.from_numpy(
            mc_evidence
        ).to(
            device=self.device
        )

        particle_map_tensor = torch.from_numpy(
            particle_map
        ).to(
            device=self.device
        )

        cluster_map_tensor = torch.from_numpy(
            cluster_map
        ).to(
            device=self.device
        )

        # ======================================================
        # 7. Final confidence
        # ======================================================

        final_confidence = float(
            np.clip(
                final_decision.final_score,
                0.0,
                1.0,
            )
        )

        global_confidence = float(
            np.clip(
                final_decision.global_evidence,
                0.0,
                1.0,
            )
        )

        # ======================================================
        # 8. Return
        # ======================================================

        return FinalMCOutput(

            mc_mask=mc_mask_tensor,

            mc_evidence=(
                mc_evidence_tensor
            ),

            particle_map=(
                particle_map_tensor
            ),

            cluster_map=(
                cluster_map_tensor
            ),

            particles=(
                final_decision
                .particle_decisions
            ),

            clusters=(
                final_decision
                .cluster_decisions
            ),

            global_confidence=(
                global_confidence
            ),

            final_confidence=(
                final_confidence
            ),

            is_microcalcification_present=(
                final_decision
                .is_microcalcification_present
            ),

            height=height,
            width=width,
        )